### ISSUE TITLE
Consider moving CONDUCT.md to .github directory

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#149]
... as that directory is already used for CONTRIBUTING.md

This was a suggestion from a reviewer of the `taxa` paper in F1000. Thoughts @sckott?

**Comment by sckott** [comment]
not sure - I've only seen it at the top level of a repo - we could experiment (at top level vs. in .github folder) and see if it gets picked up when you open a new issue in the right sidebar - it doesn't get picked up right now at all because of the thing below

related, we should change it's name to `CODE_OF_CONDUCT.md`  as github will pick it up then - e.g., https://github.com/ropensci/taxa/community they think we don't have one 😢

**Comment by zachary-foster** [comment]
This was also a "minor issue", so whatever works will be fine I think. I will try renaming it and see if it makes github happy

**Comment by zachary-foster** [comment]
Yay, github is now happy

**Comment by zachary-foster** [comment]
Github seems to still find it in the .github folder, so I think that will work and make the reviewer happy.
